# Generated by Django 2.0.13 on 2019-10-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191016_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='img/imgdef.jpg', upload_to='img/'),
        ),
    ]
